import { buildPrompt, estimateTokens, type PromptMessage } from '../shared/prompt';
import { sseData } from '../shared/sse';
import type { Book, JsonObject, Message, Settings } from '../shared/types';
import { runRoleplay } from './gateway';
import { modelInput } from './models';

export type Summary = { text: string; covered: string[]; fingerprint: string };
export async function fingerprint(history: Message[]) {
 const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(history.map(m => [m.id, m.content]))));
 return Array.from(new Uint8Array(bytes), n => n.toString(16).padStart(2, '0')).join('');
}
/** Reuse a checkpoint only for the same selected message versions and contents. */
export async function validSummary(raw: string | null | undefined, history: Message[]): Promise<Summary | null> {
 if (!raw) return null;
 try {
  const value = JSON.parse(raw) as Summary;
  if (typeof value.text !== 'string' || !value.text.trim() || !Array.isArray(value.covered) || !value.covered.length) return null;
  const covered = history.slice(0, value.covered.length);
  if (covered.length !== value.covered.length || covered.some((m, i) => m.id !== value.covered[i]) || await fingerprint(covered) !== value.fingerprint) return null;
  return value;
 } catch { return null; }
}
export function explicitContextLimit(text: string): number | undefined {
 const match = text.match(/(?:maximum context length|max(?:imum)?_model_len|context(?: window)? limit)[\s"':=]*(?:is\s+)?(\d{4,7})/i);
 const available = text.match(/(?:available|max) context size\s*\(\s*(\d{4,7})\s+tokens/i);
 const limit = Number(match?.[1] ?? available?.[1] ?? 0);
 return Number.isSafeInteger(limit) && limit >= 1024 ? limit : undefined;
}
export function contextLimit(value: unknown): number | undefined {
 if(!value || typeof value!=='object')return;
 const v=value as {error?:{n_ctx?:unknown;message?:unknown};message?:unknown};
 const n=v.error?.n_ctx;
 if(typeof n==='number' && Number.isSafeInteger(n) && n>=1024)return n;
 return explicitContextLimit(typeof v.error?.message==='string'?v.error.message:typeof v.message==='string'?v.message:'');
}
export class SummaryRetry extends Error {
 constructor(readonly contextTokens?: number) { super('会话摘要需要更小的输入'); }
}
const SUMMARY_RULE = '压缩会话记忆。只保留已发生事件、人物关系、约定和未决线索；保留否定、更正与时间顺序，不推测、不续写、不输出候选。简洁记录，显著短于原文。';
function halveStory(text:string):[string,string]{const chars=[...text];if(chars.length<2)throw Error('模型上下文无法容纳会话摘要');const middle=Math.ceil(chars.length/2);return [chars.slice(0,middle).join(''),chars.slice(middle).join('')];}
export class ConversationContext {
 summary: Summary | null = null;
 private generatedMemory = '';
 private generatedId: string | null = null;
 private wireProjection:ReturnType<typeof buildPrompt>|null=null;
 private storyFragments=new WeakSet<PromptMessage>();
 constructor(readonly history: Message[], readonly card: JsonObject, readonly books: Book[], readonly settings: Settings,
  public contextTokens: number | null, readonly options: { protocol: string; formatReminder: string; inputRatio: number; state?:string },
  readonly infer: (messages: PromptMessage[]) => Promise<string>) {}
 async restore(raw?: string | null) { this.summary = await validSummary(raw, this.history); }
 storyFragment(content:string):PromptMessage{const m:PromptMessage={role:'assistant',content};this.storyFragments.add(m);return m;}
 useProjection(messages:PromptMessage[]){this.wireProjection=this.extend({...this.prompt(),messages:messages.map(m=>structuredClone(m))},[]);}
 prompt(continuation = '', projection: { protocol: string; formatReminder: string } = this.options, suffix: PromptMessage[] = []) {
  if(this.wireProjection)return this.extend(this.wireProjection,suffix);
  const hasTools=suffix.some(m=>m.role==='tool');
  const projectedHistory=this.history.slice(this.summary?.covered.length ?? 0).filter(m=>!hasTools||m.id!==this.generatedId);
  const base = buildPrompt(this.card, this.books, projectedHistory, this.settings, this.contextTokens, hasTools?'':continuation,
   { ...this.options, ...projection, summary: [this.summary?.text, this.generatedMemory].filter(Boolean).join('\n') });
  return suffix.length ? this.extend(base, suffix) : base;
 }
 /** Preserve the actual wire prefix; temporary candidate steps never become story memory. */
 extend(base: ReturnType<typeof buildPrompt>, suffix: PromptMessage[]) {
  const messages = [...base.messages, ...suffix].map(m => ({ ...m }));
  const estimatedTokens = messages.reduce((n, m) => n + Math.ceil(estimateTokens(m.content+(m.tool_calls?JSON.stringify(m.tool_calls):'')) * this.options.inputRatio) + 8, 256);
  return { ...base, messages, estimatedTokens, needsCompression: this.contextTokens !== null && estimatedTokens > this.contextTokens };
 }
 /** Append only new model bytes; older generated bytes may already have been summarized. */
 appendOutput(message: Message, delta: string, continuing: boolean) {
  this.wireProjection=null;
  const last = this.history.at(-1);
  if (last?.id === message.id) last.content += delta;
  else if (continuing && last?.role === 'assistant') { last.id = message.id; last.content += delta; }
  else this.history.push({ ...message, content: delta });
  this.generatedId = message.id;
 }
 resume(id: string) { const last=this.history.at(-1); if(last?.role==='assistant'){last.id=id;this.generatedId=id;} }
 async fit(continuation = '', projection: { protocol: string; formatReminder: string } = this.options, suffix: PromptMessage[] = []) {
  let prompt = this.prompt(continuation, projection, suffix);
  while (prompt.needsCompression) { const before=prompt.estimatedTokens;await this.compressProjection(suffix); prompt = this.prompt(continuation, projection, suffix);if(prompt.estimatedTokens>=before)throw new Error('会话压缩未缩短输入'); }
  return prompt;
 }
 async compressProjection(suffix:PromptMessage[]){
  if(suffix.some(m=>m.role==='tool')){
   const plain=suffix.filter(m=>this.storyFragments.has(m)&&m.content.length>1);
   const largest=plain.sort((a,b)=>b.content.length-a.content.length)[0];
   const historyCost=this.history.slice(this.summary?.covered.length??0).filter(m=>m.id!==this.generatedId).reduce((n,m)=>n+estimateTokens(m.content),0);
   if(largest&&estimateTokens(largest.content)>historyCost){const [older,recent]=halveStory(largest.content);const text=await this.summarize('',[{id:'projection',role:'assistant',content:older,status:'completed',ordinal:0,requestId:null,createdAt:0}]);largest.content='已发生正文摘要：'+text+'\n'+recent;this.wireProjection=null;return;}
  }
  await this.compress();
 }
 async compress() {
  this.wireProjection=null;
  const offset = this.summary?.covered.length ?? 0, remaining = this.history.slice(offset);
  const turns: Message[][] = [];
  for (const m of remaining) { if (m.role === 'user' || !turns.length) turns.push([]); turns.at(-1)!.push(m); }
  if (turns.length >= 2) {
   const older = turns.slice(0, Math.max(1, Math.floor(turns.length / 2))).flat();
   const text = await this.summarize(this.summary?.text ?? '', older);
   const covered = this.history.slice(0, offset + older.length);
   this.summary = { text, covered: covered.map(m => m.id), fingerprint: await fingerprint(covered) };
  } else {
   const last = this.history.at(-1);
   if (last?.id === this.generatedId && last.role === 'assistant' && last.content.length > 1) {
    const [older,recent]=halveStory(last.content);
    const text = await this.summarize(this.generatedMemory, [{ ...last, content: older }]);
    this.generatedMemory = text; last.content = recent;
   } else if (this.summary) {
    this.summary = { ...this.summary, text: await this.summarize('', [{ ...remaining[0], role: 'user', content: this.summary.text }]) };
   } else throw new Error('当前输入与角色设定超过模型上下文，无法压缩历史');
  }
 }
 private async summarize(previous:string,history:Message[]){
  const options={contextTokens:this.contextTokens,inputRatio:this.options.inputRatio,infer:this.infer};
  try{return await summarizeStory(previous,history,options);}finally{this.contextTokens=options.contextTokens;}
 }

}

/** Shared algorithm; callers own separate source checkpoints and context limits. */
export async function summarizeStory(previous:string,history:Message[],options:{contextTokens:number|null;inputRatio:number;infer:(messages:PromptMessage[])=>Promise<string>;rule?:string;requireReduction?:boolean}):Promise<string>{
  const source = [previous, ...history.map(m => m.content)].filter(Boolean).join('\n');
  const messages: PromptMessage[] = [{ role: 'system', content: (options.rule ?? SUMMARY_RULE) }, {role:'user',content:[previous?'已有记忆：\n'+previous:'',...history.map(m=>(m.role==='user'?'用户：':'角色：')+m.content),options.requireReduction===false?'请简洁总结以上整体剧情。':'请压缩以上会话。摘要必须显著短于来源。'].filter(Boolean).join('\n')}];
  const cost = 256 + messages.reduce((n, m) => n + Math.ceil(estimateTokens(m.content) * options.inputRatio) + 8, 0);
  let split = options.contextTokens !== null && cost > options.contextTokens;
  if (!split) {
   try {
    const text = (await options.infer(messages)).trim();
    if (!text || options.requireReduction!==false&&text.length >= source.length) throw new Error('会话压缩未产生有效摘要');
    return text;
   } catch (error) {
    if (!(error instanceof SummaryRetry)) throw error;
    if (error.contextTokens) options.contextTokens = error.contextTokens;
    split = true;
   }
  }
  // Each retry reduces the source; no unchanged oversized summary request is repeated.
  const compressPrevious=async(content:string)=>{const reduction={...options,requireReduction:true};try{return await summarizeStory('',[{...history[0],role:'user',content}],reduction);}finally{options.contextTokens=reduction.contextTokens;}};
  const previousCost = 256 + Math.ceil(estimateTokens((options.rule ?? SUMMARY_RULE) + '已有记忆：\n' + previous) * options.inputRatio) + 16;
  if (previous && (history.length === 0 || (options.contextTokens !== null && previousCost >= options.contextTokens))) {
   const shorter = await compressPrevious(previous);
   return summarizeStory(shorter, history, options);
  }
  if (history.length > 1) {
   const middle = Math.ceil(history.length / 2);
   const first = await summarizeStory(previous, history.slice(0, middle), options);
   return summarizeStory(first, history.slice(middle), options);
  }
  const m = history[0];
  if(m&&[...m.content].length===1 && previous){const shorter=await compressPrevious(previous);return summarizeStory(shorter,history, options);}
  if (!m) throw new Error('模型上下文无法容纳会话摘要');
  const [older,recent]=halveStory(m.content);
  const first = await summarizeStory(previous, [{ ...m, content: older }], options);
  return summarizeStory(first, [{ ...m, content: recent }], options);
}

export async function summarizeWithModel(env: Env, username: string, requestId: string, settings: Settings, messages: PromptMessage[], signal: AbortSignal, observe?:(event:Parameters<import('./metrics').InferenceMetrics['observe']>[0],logId:string|null)=>void) {
 const result = await runRoleplay(env,username,requestId,{messages,stream:true,...modelInput({...settings,thinkingEnabled:false})},signal);
 if (!(result instanceof Response)) throw new Error('会话压缩失败');
 if (!result.ok) {
  const value = await result.json().catch(() => null) as { error?: { message?: string }; message?: string } | null;
  const limit = contextLimit(value);
  if (limit) throw new SummaryRetry(limit);
  throw new Error('会话压缩失败');
 }
 if (!result.body || !result.headers.get('Content-Type')?.includes('text/event-stream')) { await result.body?.cancel(); throw new Error('会话压缩失败'); }
 let text = '', finish = '';
 for await (const data of sseData(result.body, signal)) {
  if (data === '[DONE]') break;
  const event = JSON.parse(data);observe?.(event,result.headers.get('cf-aig-log-id'));
  if (event.error) { const limit = contextLimit(event); if (limit) throw new SummaryRetry(limit); throw new Error('会话压缩失败'); }
  const c = event.choices?.[0];
  if (typeof c?.delta?.content === 'string') text += c.delta.content;
  if (c?.finish_reason) finish = c.finish_reason;
 }
 if (signal.aborted) throw new Error('会话压缩已停止');
 if (finish === 'length') throw new SummaryRetry();
 if (finish !== 'stop') throw new Error('会话压缩未完成');
 return text;
}
