import { buildPrompt, estimateTokens, type PromptMessage } from '../shared/prompt';
import { sseData } from '../shared/sse';
import type { Book, JsonObject, Message, Settings } from '../shared/types';
import { roleplayGatewayOptions } from './gateway';
import { modelInput } from './models';

export type Summary = { text: string; covered: string[]; fingerprint: string };
async function fingerprint(history: Message[]) {
 const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(history.map(m => [m.id, m.content]))));
 return Array.from(new Uint8Array(bytes), n => n.toString(16).padStart(2, '0')).join('');
}
/** Reuse a checkpoint only for the same selected message versions and contents. */
export async function validSummary(raw: string | null | undefined, history: Message[]): Promise<Summary | null> {
 if (!raw) return null;
 try {
  const value = JSON.parse(raw) as Summary;
  if (typeof value.text !== 'string' || !value.text.trim() || !Array.isArray(value.covered) || !value.covered.length) return null;
  const covered = history.slice(0, value.covered.length);
  if (covered.length !== value.covered.length || covered.some((m, i) => m.id !== value.covered[i]) || await fingerprint(covered) !== value.fingerprint) return null;
  return value;
 } catch { return null; }
}
export function explicitContextLimit(text: string): number | undefined {
 const match = text.match(/(?:maximum context length|max(?:imum)?_model_len|context(?: window)? limit)[\s"':=]*(?:is\s+)?(\d{4,7})/i);
 const available = text.match(/(?:available|max) context size\s*\(\s*(\d{4,7})\s+tokens/i);
 const limit = Number(match?.[1] ?? available?.[1] ?? 0);
 return Number.isSafeInteger(limit) && limit >= 1024 ? limit : undefined;
}
export function contextLimit(value: unknown): number | undefined {
 if(!value || typeof value!=='object')return;
 const v=value as {error?:{n_ctx?:unknown;message?:unknown};message?:unknown};
 const n=v.error?.n_ctx;
 if(typeof n==='number' && Number.isSafeInteger(n) && n>=1024)return n;
 return explicitContextLimit(typeof v.error?.message==='string'?v.error.message:typeof v.message==='string'?v.message:'');
}
export class SummaryRetry extends Error {
 constructor(readonly contextTokens?: number) { super('会话摘要需要更小的输入'); }
}
const SUMMARY_RULE = '压缩会话记忆。只保留已发生事件、人物关系、约定和未决线索；保留否定、更正与时间顺序，不推测、不续写、不输出候选。简洁记录，显著短于原文。';
export class ConversationContext {
 summary: Summary | null = null;
 private generatedMemory = '';
 private generatedId: string | null = null;
 constructor(readonly history: Message[], readonly card: JsonObject, readonly books: Book[], readonly settings: Settings,
  public contextTokens: number | null, readonly options: { protocol: string; formatReminder: string; inputRatio: number },
  readonly infer: (messages: PromptMessage[]) => Promise<string>) {}
 async restore(raw?: string | null) { this.summary = await validSummary(raw, this.history); }
 prompt(continuation = '', projection: { protocol: string; formatReminder: string } = this.options) {
  return buildPrompt(this.card, this.books, this.history.slice(this.summary?.covered.length ?? 0), this.settings, this.contextTokens, continuation,
   { ...this.options, ...projection, summary: [this.summary?.text, this.generatedMemory].filter(Boolean).join('\n') });
 }
 /** Append only new model bytes; older generated bytes may already have been summarized. */
 appendOutput(message: Message, delta: string, continuing: boolean) {
  const last = this.history.at(-1);
  if (last?.id === message.id) last.content += delta;
  else if (continuing && last?.role === 'assistant') { last.id = message.id; last.content += delta; }
  else this.history.push({ ...message, content: delta });
  this.generatedId = message.id;
 }
 resume(id: string) { const last=this.history.at(-1); if(last?.role==='assistant'){last.id=id;this.generatedId=id;} }
 async fit(continuation = '', projection: { protocol: string; formatReminder: string } = this.options) {
  let prompt = this.prompt(continuation, projection);
  while (prompt.needsCompression) { const before=prompt.estimatedTokens;await this.compress(); prompt = this.prompt(continuation, projection);if(prompt.estimatedTokens>=before)throw new Error('会话压缩未缩短输入'); }
  return prompt;
 }
 async compress() {
  const offset = this.summary?.covered.length ?? 0, remaining = this.history.slice(offset);
  const turns: Message[][] = [];
  for (const m of remaining) { if (m.role === 'user' || !turns.length) turns.push([]); turns.at(-1)!.push(m); }
  if (turns.length >= 2) {
   const older = turns.slice(0, Math.max(1, Math.floor(turns.length / 2))).flat();
   const text = await this.summarize(this.summary?.text ?? '', older);
   const covered = this.history.slice(0, offset + older.length);
   this.summary = { text, covered: covered.map(m => m.id), fingerprint: await fingerprint(covered) };
  } else {
   const last = this.history.at(-1);
   if (last?.id === this.generatedId && last.role === 'assistant' && last.content.length > 1) {
    const split = Math.floor(last.content.length / 2);
    const text = await this.summarize(this.generatedMemory, [{ ...last, content: last.content.slice(0, split) }]);
    this.generatedMemory = text; last.content = last.content.slice(split);
   } else if (this.summary) {
    this.summary = { ...this.summary, text: await this.summarize('', [{ ...remaining[0], role: 'user', content: this.summary.text }]) };
   } else throw new Error('当前输入与角色设定超过模型上下文，无法压缩历史');
  }
 }
 private async summarize(previous: string, history: Message[]): Promise<string> {
  const source = [previous, ...history.map(m => m.content)].filter(Boolean).join('\n');
  const messages: PromptMessage[] = [{ role: 'system', content: SUMMARY_RULE }, {role:'user',content:[previous?'已有记忆：\n'+previous:'',...history.map(m=>(m.role==='user'?'用户：':'角色：')+m.content),'请压缩以上会话。'].filter(Boolean).join('\n')}];
  const cost = 256 + messages.reduce((n, m) => n + Math.ceil(estimateTokens(m.content) * this.options.inputRatio) + 8, 0);
  let split = this.contextTokens !== null && cost > this.contextTokens;
  if (!split) {
   try {
    const text = (await this.infer(messages)).trim();
    if (!text || text.length >= source.length) throw new Error('会话压缩未产生有效摘要');
    return text;
   } catch (error) {
    if (!(error instanceof SummaryRetry)) throw error;
    if (error.contextTokens) this.contextTokens = error.contextTokens;
    split = true;
   }
  }
  // Each retry reduces the source; no unchanged oversized summary request is repeated.
  const previousCost = 256 + Math.ceil(estimateTokens(SUMMARY_RULE + '已有记忆：\n' + previous) * this.options.inputRatio) + 16;
  if (previous && (history.length === 0 || (this.contextTokens !== null && previousCost >= this.contextTokens))) {
   const shorter = await this.summarize('', [{ ...history[0], role: 'user', content: previous }]);
   return this.summarize(shorter, history);
  }
  if (history.length > 1) {
   const middle = Math.ceil(history.length / 2);
   const first = await this.summarize(previous, history.slice(0, middle));
   return this.summarize(first, history.slice(middle));
  }
  const m = history[0];
  if(m?.content.length===1 && previous){const shorter=await this.summarize('',[{...m,role:'user',content:previous}]);return this.summarize(shorter,history);}
  if (!m || m.content.length < 2) throw new Error('模型上下文无法容纳会话摘要');
  const middle = Math.ceil(m.content.length / 2);
  const first = await this.summarize(previous, [{ ...m, content: m.content.slice(0, middle) }]);
  return this.summarize(first, [{ ...m, content: m.content.slice(middle) }]);
 }
}

export async function summarizeWithModel(env: Env, username: string, requestId: string, settings: Settings, messages: PromptMessage[], signal: AbortSignal) {
 const opts = roleplayGatewayOptions(env, username, requestId);
 const result = await env.AI.gateway(env.AIG_GATEWAY_ID).run({ provider: 'compat', endpoint: 'chat/completions', headers: { ...opts.extraHeaders, 'Content-Type': 'application/json' },
  query: { model: 'dynamic/rp', messages, stream: true, ...modelInput({ ...settings, thinkingEnabled: false }) } }, { gateway: opts.gateway, signal });
 if (!(result instanceof Response)) throw new Error('会话压缩失败');
 if (!result.ok) {
  const value = await result.json().catch(() => null) as { error?: { message?: string }; message?: string } | null;
  const limit = contextLimit(value);
  if (limit) throw new SummaryRetry(limit);
  throw new Error('会话压缩失败');
 }
 if (!result.body || !result.headers.get('Content-Type')?.includes('text/event-stream')) { await result.body?.cancel(); throw new Error('会话压缩失败'); }
 let text = '', finish = '';
 for await (const data of sseData(result.body, signal)) {
  if (data === '[DONE]') break;
  const event = JSON.parse(data);
  if (event.error) { const limit = contextLimit(event); if (limit) throw new SummaryRetry(limit); throw new Error('会话压缩失败'); }
  const c = event.choices?.[0];
  if (typeof c?.delta?.content === 'string') text += c.delta.content;
  if (c?.finish_reason) finish = c.finish_reason;
 }
 if (signal.aborted) throw new Error('会话压缩已停止');
 if (finish === 'length') throw new SummaryRetry();
 if (finish !== 'stop') throw new Error('会话压缩未完成');
 return text;
}
