<script lang="ts">
 import { onMount, onDestroy, tick } from 'svelte';import { Button } from '@hasbai/ui/button';import * as Dialog from '@hasbai/ui/dialog';
 import { MessageCircle, Send, Square, RefreshCw, Pencil, Download, Trash2, SlidersHorizontal, ChevronLeft } from '@lucide/svelte';
 import type { Api } from '../lib/api';import type { Message, Session, Worldbook } from '../../shared/types';import Confirm from '../lib/Confirm.svelte';
 let {api,initialId='',onlibrary}:{api:Api;initialId?:string;onlibrary:()=>void}=$props();
 let sessions=$state<Session[]>([]),active=$state<Session>(),messages=$state<Message[]>([]),loading=$state(true),error=$state(''),busy=$state(false),generating=$state(false),text=$state(''),mobileList=$state(true),config=$state(false),configDraft=$state<Session>(),books=$state<Worldbook[]>([]),edit=$state(false),editMessage=$state<Message>(),editText=$state(''),deleteOpen=$state(false);let abort:AbortController|undefined;let log=$state<HTMLDivElement>();let alive=true;let generationId='';let poll:ReturnType<typeof setTimeout>|undefined;
 onMount(()=>{void load();});onDestroy(()=>{alive=false;abort?.abort();if(poll)clearTimeout(poll);});
 async function load(){loading=true;error='';try{sessions=(await api.request<{sessions:Session[]}>('sessions')).sessions;if(initialId)await select(initialId);}catch(e){error=(e as Error).message;}finally{loading=false;}}
 async function select(id:string){if(generating)return;busy=true;error='';try{const d=await api.request<{session:Session;messages:Message[]}>('sessions/'+id);active=d.session;messages=d.messages;generationId=d.session.generationId??'';if(poll)clearTimeout(poll);if(generationId&&!generating)poll=setTimeout(()=>{if(alive&&active?.id===id)void select(id);},1200);mobileList=false;await tick();scroll();}catch(e){error=(e as Error).message;}finally{busy=false;}}
 function scroll(){if(log)log.scrollTop=log.scrollHeight;}
 async function send(regenerate=false){if(!active||generating||busy||(!regenerate&&!text.trim()))return;error='';generating=true;abort=new AbortController();const requestId=crypto.randomUUID(),sessionId=active.id;let pending='';const content=text;
  if(!regenerate)text='';
  try{await api.generate(sessionId,{requestId,content,regenerate},e=>{if(!alive)return;
   if(e.type==='start'){pending=e.messageId;generationId=e.messageId;if(active)active.generationId=e.messageId;if(!regenerate)messages=[...messages,{id:'local-user',role:'user',content,status:'completed',ordinal:messages.length,requestId,createdAt:Date.now()}];messages=[...messages,{id:pending,role:'assistant',content:'',status:'pending',ordinal:messages.length,requestId,createdAt:Date.now()}];}
   if(e.type==='delta')messages=messages.map(m=>m.id===pending?{...m,content:m.content+e.text}:m);
   if(e.type==='error')error=e.message;
   if(e.type==='done')messages=messages.map(m=>m.id===pending?e.message:m);
   void tick().then(scroll);
  },abort.signal);}catch(e){if(alive&&!abort.signal.aborted){error=(e as Error).message;if(!pending&&!regenerate)text=content;}}
  finally{if(alive){generating=false;generationId='';if(active)active.generationId=null;const failure=error;await select(sessionId);error=failure;sessions=(await api.request<{sessions:Session[]}>('sessions').catch(()=>({sessions}))).sessions;}}
 }
 async function stop(){if(!active||!generationId)return;error='';try{await api.request('sessions/'+active.id+'/stop','POST',{generationId});abort?.abort();if(!generating)await select(active.id);}catch(e){error=(e as Error).message;}}
 async function openConfig(){if(!active)return;busy=true;error='';try{books=(await api.request<{worldbooks:Worldbook[]}>('worldbooks')).worldbooks;configDraft=structuredClone($state.snapshot(active));config=true;}catch(e){error=(e as Error).message;}finally{busy=false;}}
 async function saveConfig(){if(!active||!configDraft)return;busy=true;error='';try{active=await api.request<Session>('sessions/'+active.id,'PATCH',{title:configDraft.title,settings:configDraft.settings,bookIds:configDraft.bookIds});config=false;}catch(e){error=(e as Error).message;}finally{busy=false;}}
 async function fork(){if(!active||!editMessage)return;busy=true;error='';try{const s=await api.request<Session>('sessions/'+active.id+'/fork','POST',{messageId:editMessage.id,content:editText});edit=false;sessions=[s,...sessions];await select(s.id);}catch(e){error=(e as Error).message;}finally{busy=false;}}
 async function remove(){if(!active)return;busy=true;error='';try{await api.request('sessions/'+active.id,'DELETE');sessions=sessions.filter(s=>s.id!==active!.id);active=undefined;messages=[];deleteOpen=false;mobileList=true;}catch(e){error=(e as Error).message;}finally{busy=false;}}
 function toggleBook(id:string,checked:boolean){if(configDraft)configDraft.bookIds=checked?[...configDraft.bookIds,id]:configDraft.bookIds.filter(i=>i!==id);}
</script>
<div class="chat-workspace" class:show-list={mobileList}>
 <aside class="conversation-list"><div class="list-heading"><h1>对话 <span class="count">{sessions.length}</span></h1><Button variant="ghost" aria-label="新建对话" onclick={onlibrary}><MessageCircle size={18}/></Button></div>{#if error&&!active}<p class="error" role="alert">{error}<Button variant="outline" onclick={load}>重试</Button></p>{/if}{#if loading}<p role="status" class="muted">正在加载对话…</p>{/if}{#each sessions as s(s.id)}<button class="conversation" aria-current={active?.id===s.id?'page':undefined} disabled={generating} onclick={()=>select(s.id)}><strong>{s.title}</strong><span>{s.characterName}</span></button>{/each}{#if !loading&&!sessions.length}<Button variant="outline" onclick={onlibrary}>选择角色</Button>{/if}</aside>
 <section class="chat-main" aria-label="角色对话">
  {#if active}<header class="chat-header"><div class="actions"><Button class="mobile-back" variant="ghost" aria-label="返回会话列表" disabled={generating} onclick={()=>mobileList=true}><ChevronLeft size={18}/></Button><div><h2>{active.title}</h2><span class="muted">{active.characterName}</span></div></div><div class="actions"><Button variant="ghost" aria-label="会话设置" disabled={generating||busy||!!active.generationId} onclick={openConfig}><SlidersHorizontal size={18}/></Button><Button variant="ghost" aria-label="导出对话" onclick={()=>api.download('sessions/'+active!.id+'/export',active!.title+'.jsonl').catch(e=>error=e.message)}><Download size={18}/></Button><Button variant="ghost" aria-label="删除会话" disabled={generating||busy||!!active.generationId} onclick={()=>deleteOpen=true}><Trash2 size={18}/></Button></div></header>
   {#if error}<p class="error" role="alert">{error}</p>{/if}
   <div class="message-log" bind:this={log} role="log" aria-label="消息历史" aria-live="off">{#each messages as m(m.id)}<article class="message" class:from-user={m.role==='user'}><div class="message-heading"><strong>{m.role==='user'?active.settings.userName:active.characterName}</strong>{#if m.status!=='completed'}<span class="status">{m.status==='pending'?'生成中':m.status==='aborted'?'已停止':'生成失败'}</span>{/if}{#if m.status==='completed'}<Button variant="ghost" aria-label={`编辑第 ${m.ordinal+1} 条消息`} disabled={generating||busy||!!active.generationId} onclick={()=>{editMessage=m;editText=m.content;edit=true;}}><Pencil size={14}/></Button>{/if}</div><p class="message-text">{m.content|| (m.status==='pending'?'…':'')}</p></article>{/each}</div>
   <form class="composer" onsubmit={e=>{e.preventDefault();void send();}}><label class="sr-only" for="message-input">发送消息</label><textarea id="message-input" bind:value={text} placeholder="写下你的行动或对白…" rows="3" maxlength={24000} disabled={generating||busy||!!active.generationId} onkeydown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();void send();}}}></textarea><div class="composer-actions"><Button type="button" variant="ghost" disabled={generating||busy||!!active.generationId||!messages.some(m=>m.role==='user'&&m.status==='completed')} onclick={()=>send(true)}><RefreshCw size={16}/>重新生成</Button>{#if generating||active.generationId}<Button type="button" variant="outline" onclick={stop}><Square size={16}/>停止</Button>{:else}<Button type="submit" disabled={!text.trim()||busy}><Send size={16}/>发送</Button>{/if}</div></form>
  {:else}<div class="empty chat-empty"><MessageCircle size={36}/><h2>故事从这里开始</h2><Button onclick={onlibrary}>选择角色</Button></div>{/if}
 </section>
</div>
<Dialog.Root bind:open={config}><Dialog.Content><Dialog.Header><Dialog.Title>会话设置</Dialog.Title></Dialog.Header>{#if configDraft}<div class="stack detail-body"><div class="field"><label for="session-title">会话名称</label><input id="session-title" bind:value={configDraft.title} maxlength="120"/></div><div class="field"><label for="session-name">你的名字</label><input id="session-name" bind:value={configDraft.settings.userName} maxlength="80"/></div><div class="field"><label for="session-persona">你的角色设定</label><textarea id="session-persona" bind:value={configDraft.settings.persona} rows="4" maxlength="12000"></textarea></div><h2>世界书</h2>{#each books as b}<label class="checkbox-row"><input type="checkbox" disabled={!b.enabled} checked={configDraft.bookIds.includes(b.id)} onchange={e=>toggleBook(b.id,e.currentTarget.checked)}/>{b.name}<span class="muted">{b.enabled?`${b.count} 条`:'已停用'}</span></label>{/each}{#if !books.length}<Button variant="outline" onclick={()=>config=false}>关闭</Button>{/if}</div>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}<Dialog.Footer><Button variant="outline" disabled={busy} onclick={()=>config=false}>取消</Button><Button disabled={busy} onclick={saveConfig}>保存</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
<Dialog.Root bind:open={edit}><Dialog.Content><Dialog.Header><Dialog.Title>编辑并创建分支</Dialog.Title></Dialog.Header><label for="edit-message">消息内容</label><textarea id="edit-message" bind:value={editText} rows="10" maxlength="24000"></textarea>{#if error}<p class="error" role="alert">{error}</p>{/if}<Dialog.Footer><Button variant="outline" disabled={busy} onclick={()=>edit=false}>取消</Button><Button disabled={busy||!editText.trim()} onclick={fork}>创建分支</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
<Confirm bind:open={deleteOpen} title={`删除会话「${active?.title??''}」？`} {busy} onconfirm={remove}/>
