<script lang="ts">
 import { Button } from '@hasbai/ui/button'; import { Input } from '@hasbai/ui/input'; import { Search, Download, Check, ExternalLink } from '@lucide/svelte';
 import type { Api } from '../lib/api'; import type { Discovery } from '../../shared/types';
 let {api}:{api:Api}=$props();
 let query=$state(''),source=$state('theatrelm'),page=$state(1),data=$state<Discovery>(),loading=$state(false),error=$state(''),installing=$state(''),installed=$state<string[]>([]),started=$state(false);
 async function search(next=1){loading=true;error='';started=true;page=next;try{data=await api.request<Discovery>('discover?'+new URLSearchParams({q:query,source,page:String(page)}));}catch(e){error=(e as Error).message;data=undefined;}finally{loading=false;}}
 async function install(id:string){installing=id;error='';try{await api.request('install','POST',{source:data!.source,id});installed=[...installed,`${data!.source}:${id}`];}catch(e){error=(e as Error).message;}finally{installing='';}}
</script>
<header class="page-head"><div><p class="eyebrow">DISCOVER A STORY</p><h1>发现角色</h1></div></header>
<form class="discover-search" onsubmit={e=>{e.preventDefault();void search();}}><div class="field"><label for="source">角色来源</label><select id="source" bind:value={source} disabled={loading}><option value="theatrelm">TheatreLM · Hugging Face</option><option value="chub">Chub</option></select></div><div class="field search-grow"><label for="discover-query">关键词</label><Input id="discover-query" bind:value={query} maxlength={150} placeholder="角色名称、故事或世界"/></div><Button type="submit" disabled={loading}><Search size={16}/>{loading?'搜索中…':'搜索'}</Button></form>
{#if error}<div class="error" role="alert">{error}<Button variant="outline" disabled={loading} onclick={()=>search(page)}>重试</Button></div>{/if}
{#if loading}<div class="empty" role="status">正在搜索角色…</div>{:else if data?.results.length}<div class="results-head"><h2>搜索结果</h2><span class="muted">第 {data.page} 页</span></div><div class="card-grid">{#each data.results as c(`${c.source}:${c.id}`)}<article class="character-card"><div class="result-avatar" aria-hidden="true">{c.name.slice(0,1)}</div><h2>{c.name}</h2><p class="muted">{c.creator}</p><p class="description">{c.description}</p><div class="tags">{#each c.tags.slice(0,3) as tag}<span>{tag}</span>{/each}</div><div class="actions"><Button class="grow" variant="outline" disabled={!!installing||installed.includes(`${c.source}:${c.id}`)} onclick={()=>install(c.id)}>{#if installed.includes(`${c.source}:${c.id}`)}<Check size={16}/>已安装{:else}<Download size={16}/>{installing===c.id?'安装中…':'安装'}{/if}</Button><a class="icon-link" href={c.sourceUrl} aria-label={`查看 ${c.name} 来源`} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/></a></div></article>{/each}</div><div class="pagination"><Button variant="outline" disabled={page===1||loading} onclick={()=>search(page-1)}>上一页</Button><span>{page}</span><Button variant="outline" disabled={!data.hasMore||loading} onclick={()=>search(page+1)}>下一页</Button></div>{:else if started&&!error}<div class="empty"><Search size={32}/><h2>没有匹配的角色</h2><Button variant="outline" onclick={()=>{query='';void search();}}>浏览全部</Button></div>{:else if !error}<div class="empty"><Search size={32}/><h2>寻找下一段故事</h2><Button variant="outline" onclick={()=>search()}>浏览角色</Button></div>{/if}
