<script lang="ts">
 import { Notice } from '@hasbai/ui/notice';
 import { onMount } from 'svelte';
 import { Button } from '@hasbai/ui/button';import { Input } from '@hasbai/ui/input';import { Search,Download,Check,ExternalLink,Star } from '@lucide/svelte';
 import type { Api } from '../lib/api';import type { Discovery } from '../../shared/types';
 let {api}:{api:Api}=$props();
 const categories=[['Fantasy','奇幻'],['Romance','恋爱'],['RPG','角色扮演'],['Adventure','冒险'],['Anime','动漫'],['Game Characters','游戏'],['OC','原创'],['Scenario','情景'],['Comedy','喜剧'],['Mystery','悬疑'],['Sci-Fi','科幻']];
 let query=$state(''),source=$state('chub'),sort=$state('popular'),category=$state(''),tags=$state(''),page=$state(1),data=$state<Discovery>(),loading=$state(false),error=$state(''),installing=$state(''),installed=$state<string[]>([]);let searchId=0;
 onMount(()=>{void search();});
 async function search(next=1){const id=++searchId;loading=true;error='';page=next;try{const selected=[...new Set([category,...tags.split(',').map(t=>t.trim())].filter(Boolean))];const result=await api.request<Discovery>('discover?'+new URLSearchParams({q:query,source,page:String(next),sort,tags:selected.join(',')}));if(id===searchId)data=result;}catch(e){if(id===searchId){error=(e as Error).message;data=undefined;}}finally{if(id===searchId)loading=false;}}
 function changeSource(){sort=source==='chub'?'popular':'catalog';category='';tags='';void search();}
 async function install(id:string){if(!data)return;const provider=data.source;installing=id;error='';try{await api.request('install','POST',{source:provider,id});installed=[...installed,`${provider}:${id}`];}catch(e){error=(e as Error).message;}finally{installing='';}}
 const date=(value?:string)=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'short',day:'numeric',timeZone:'Asia/Shanghai'}).format(new Date(value)):'';
</script>
<header class="page-head"><div><p class="eyebrow">DISCOVER A STORY</p><h1>发现角色</h1></div></header>
<form class="discover-search" onsubmit={e=>{e.preventDefault();void search();}}>
 <div class="field"><label for="source">角色来源</label><select id="source" bind:value={source} disabled={loading} onchange={changeSource}><option value="chub">Chub</option><option value="theatrelm">TheatreLM · Hugging Face</option></select></div>
 <div class="field search-grow"><label for="discover-query">关键词</label><Input id="discover-query" bind:value={query} maxlength={150} placeholder="角色名称、故事或世界"/></div><Button type="submit" disabled={loading}><Search size={16}/>{loading?'搜索中…':'搜索'}</Button>
 <div class="discover-filters"><div class="field"><label for="discover-sort">排序</label><select id="discover-sort" bind:value={sort} disabled={loading||source!=='chub'} onchange={()=>search()}>{#if source==='chub'}<option value="popular">热度</option><option value="trending">近期热门</option><option value="newest">最新发布</option><option value="updated">最近更新</option><option value="rating">评分</option>{:else}<option value="catalog">目录顺序</option>{/if}</select></div>
 <div class="field"><label for="discover-category">分类</label><select id="discover-category" bind:value={category} disabled={loading||source!=='chub'} onchange={()=>search()}><option value="">全部分类</option>{#each categories as [value,label]}<option {value}>{label}</option>{/each}</select></div>
 <details class="discover-tags"><summary>更多标签</summary><div class="field"><label for="discover-tags">标签</label><Input id="discover-tags" bind:value={tags} disabled={loading||source!=='chub'} maxlength={360} placeholder="Fantasy, OC"/></div></details></div>
</form>
{#if error}<Notice variant="error">{error}<Button variant="outline" disabled={loading} onclick={()=>search(page)}>重试</Button></Notice>{/if}
{#if loading}<div class="empty" role="status">正在搜索角色…</div>{:else if data?.results.length}
 <div class="results-head"><h2>搜索结果 <span class="count">{data.total??''}</span></h2><span class="muted">第 {data.page} 页</span></div><div class="card-grid discover-grid">{#each data.results as c(`${c.source}:${c.id}`)}<article class="character-card discover-card"><div class="result-cover">{#if c.avatarUrl}<img src={c.avatarUrl} alt="" loading="lazy" referrerpolicy="no-referrer" onerror={e=>e.currentTarget.setAttribute('hidden','')}/>{/if}<span class="result-avatar" aria-hidden="true">{c.name.slice(0,1)}</span></div><div class="result-heading"><h2>{c.name}</h2><p class="muted">{c.creator}</p></div><p class="description">{c.description}</p><div class="tags">{#each c.tags.slice(0,3) as tag}<button type="button" onclick={()=>{tags=tag;category='';void search();}}>{tag}</button>{/each}</div><div class="result-meta">{#if c.popularity!==undefined}<span aria-label={`${c.popularity} 次下载`}><Star size={13}/>{new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(c.popularity)}</span>{/if}{#if date(sort==='updated'?c.updatedAt:c.createdAt)}<time>{date(sort==='updated'?c.updatedAt:c.createdAt)}</time>{/if}</div><div class="actions"><Button class="grow" variant="outline" disabled={!!installing||installed.includes(`${c.source}:${c.id}`)} onclick={()=>install(c.id)}>{#if installed.includes(`${c.source}:${c.id}`)}<Check size={16}/>已安装{:else}<Download size={16}/>{installing===c.id?'安装中…':'安装'}{/if}</Button><a class="icon-link" href={c.sourceUrl} aria-label={`查看 ${c.name} 来源`} target="_blank" rel="noopener noreferrer"><ExternalLink size={17}/></a></div></article>{/each}</div><div class="pagination"><Button variant="outline" disabled={page===1||loading} onclick={()=>search(page-1)}>上一页</Button><span>{page}</span><Button variant="outline" disabled={!data.hasMore||loading} onclick={()=>search(page+1)}>下一页</Button></div>
{:else if !error}<div class="empty"><Search size={32}/><h2>没有匹配的角色</h2><Button variant="outline" onclick={()=>{query='';category='';tags='';void search();}}>浏览全部</Button></div>{/if}
