<script lang="ts">
 import { onMount } from 'svelte';
 import { Button } from '@hasbai/ui/button'; import { Input } from '@hasbai/ui/input'; import * as Dialog from '@hasbai/ui/dialog';
 import { Plus, Upload, MessageCircle, Download, Trash2, Pencil } from '@lucide/svelte';
 import type { Api } from '../lib/api'; import type { Character, JsonObject } from '../../shared/types'; import { parseCard } from '../../shared/cards';
 import Avatar from '../lib/Avatar.svelte'; import Confirm from '../lib/Confirm.svelte';
 let {api,onchat}:{api:Api;onchat:(id:string,greeting:number)=>Promise<void>}=$props();
 let cards=$state<Character[]>([]),query=$state(''),loading=$state(true),error=$state(''),busy=$state(false),editor=$state(false),detail=$state<Character>(),editingCharacter=$state<Character>(),draft=$state(''),editorError=$state(''),deleting=$state<Character>(),deleteOpen=$state(false),greeting=$state(0); let input:HTMLInputElement;
 let filtered=$derived(cards.filter(c=>`${c.name} ${c.creator} ${c.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())));
 onMount(()=>{void load();});
 async function load(){loading=true;error='';try{cards=(await api.request<{characters:Character[]}>('characters')).characters;}catch(e){error=(e as Error).message;}finally{loading=false;}}
 async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;busy=true;error='';try{await api.upload('characters',file);await load();}catch(e){error=(e as Error).message;}finally{busy=false;input.value='';}}
 async function show(c:Character){busy=true;error='';try{detail=await api.request<Character>('characters/'+c.id);greeting=0;}catch(e){error=(e as Error).message;}finally{busy=false;}}
 function create(){detail=undefined;editingCharacter=undefined;editorError='';draft=JSON.stringify({spec:'chara_card_v2',spec_version:'2.0',data:{name:'',description:'',personality:'',scenario:'',first_mes:'',mes_example:'',creator_notes:'',system_prompt:'',post_history_instructions:'',alternate_greetings:[],tags:[],creator:'',character_version:'',extensions:{}}},null,2);editor=true;}
 async function save(){busy=true;editorError='';try{let raw:JsonObject;try{raw=JSON.parse(draft) as JsonObject;}catch{throw new Error('JSON 格式无效');}parseCard(raw);if(editingCharacter)await api.request('characters/'+editingCharacter.id,'PATCH',{card:raw});else await api.upload('characters',new File([JSON.stringify(raw)],'character.json',{type:'application/json'}));editor=false;detail=undefined;await load();}catch(e){editorError=(e as Error).message;}finally{busy=false;}}
 async function remove(){if(!deleting)return;busy=true;try{await api.request('characters/'+deleting.id,'DELETE');deleting=undefined;deleteOpen=false;detail=undefined;await load();}catch(e){error=(e as Error).message;}finally{busy=false;}}
 const cardData=$derived(detail?.card?parseCard(detail.card).data:undefined);
</script>
<header class="page-head"><div><p class="eyebrow">YOUR CAST</p><h1>角色库 <span class="count">{cards.length}</span></h1></div><div class="actions"><Button variant="outline" disabled={busy} onclick={()=>input.click()}><Upload size={16}/>导入</Button><Button onclick={create}><Plus size={16}/>创建角色</Button></div></header>
<input class="sr-only" tabindex="-1" bind:this={input} type="file" accept=".json,.png,.charx" aria-label="导入角色卡" onchange={upload}/>
<label class="search-label" for="library-search">搜索角色</label><Input id="library-search" bind:value={query} placeholder="角色、作者或标签"/>
{#if error}<div class="error" role="alert">{error}<Button variant="outline" onclick={load}>重试</Button></div>{/if}
{#if loading}<div class="empty" role="status">正在加载角色…</div>{:else if !error&&!filtered.length}<div class="empty"><MessageCircle size={32}/><h2>{query?'没有匹配的角色':'角色库为空'}</h2><Button variant="outline" onclick={()=>input.click()}>导入角色卡</Button></div>{:else if !error}<div class="card-grid">{#each filtered as c(c.id)}<article class="character-card"><button class="card-main" disabled={busy} onclick={()=>show(c)}><Avatar {api} id={c.id} name={c.name} available={c.hasAvatar}/><div class="card-title"><h2>{c.name}</h2><span class="muted">{c.creator||'未署名'}</span></div><p class="description">{c.description}</p><div class="tags"><span>{c.format}</span>{#each c.tags.slice(0,3) as tag}<span>{tag}</span>{/each}</div></button><Button variant="outline" disabled={busy} onclick={()=>onchat(c.id,0)}><MessageCircle size={16}/>开始对话</Button></article>{/each}</div>{/if}
<Dialog.Root open={!!detail&&!editor} onOpenChange={(open)=>{if(!open)detail=undefined;}}><Dialog.Content><Dialog.Header><Dialog.Title>{detail?.name}</Dialog.Title></Dialog.Header>{#if detail&&cardData}<div class="stack detail-body"><p class="preserve">{cardData.description}</p>{#if cardData.personality}<h2>性格</h2><p class="preserve">{cardData.personality}</p>{/if}{#if cardData.scenario}<h2>场景</h2><p class="preserve">{cardData.scenario}</p>{/if}{#if cardData.creator_notes}<h2>作者备注</h2><p class="preserve">{String(cardData.creator_notes)}</p>{/if}{#if detail.sourceUrl}<a href={detail.sourceUrl} target="_blank" rel="noopener noreferrer">角色来源</a>{/if}{#if detail.unsupported.length}<div class="tags"><span>扩展仅保留</span>{#each detail.unsupported as item}<span>{item}</span>{/each}</div>{/if}<label for="greeting">开场白</label><select id="greeting" bind:value={greeting}>{#each [cardData.first_mes,...cardData.alternate_greetings] as text,i}<option value={i}>{i+1} · {text.slice(0,60)||'空开场'}</option>{/each}</select><p class="preserve">{[cardData.first_mes,...cardData.alternate_greetings][greeting]}</p></div><Dialog.Footer><div class="actions"><Button variant="outline" aria-label="编辑角色" onclick={()=>{editingCharacter=detail;draft=JSON.stringify(detail!.card,null,2);detail=undefined;editorError='';editor=true;}}><Pencil size={16}/></Button><Button variant="outline" aria-label="导出角色 JSON" onclick={()=>api.download('characters/'+detail!.id+'/export',detail!.name+'.json').catch(e=>error=e.message)}><Download size={16}/></Button><Button variant="outline" aria-label="导出原文件" onclick={()=>api.download('characters/'+detail!.id+'/export?original=true',detail!.originalFilename||detail!.name+'.json').catch(e=>error=e.message)}><Download size={16}/><span>原卡</span></Button><Button variant="outline" aria-label="删除角色" onclick={()=>{deleting=detail;deleteOpen=true;}}><Trash2 size={16}/></Button><Button disabled={busy} onclick={async()=>{const c=detail!;detail=undefined;await onchat(c.id,greeting);}}>开始对话</Button></div></Dialog.Footer>{/if}</Dialog.Content></Dialog.Root>
<Dialog.Root open={editor} onOpenChange={(open)=>{editor=open;if(!open)editingCharacter=undefined;}}><Dialog.Content><Dialog.Header><Dialog.Title>{editingCharacter?'编辑角色':'创建角色'}</Dialog.Title></Dialog.Header><label for="card-json">角色卡 JSON</label><textarea id="card-json" class="code-editor" bind:value={draft} spellcheck="false"></textarea>{#if editorError}<p role="alert" class="error">{editorError}</p>{/if}<Dialog.Footer><Button variant="outline" disabled={busy} onclick={()=>editor=false}>取消</Button><Button disabled={busy} onclick={save}>{busy?'保存中…':'保存'}</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
<Confirm bind:open={deleteOpen} title={`删除角色「${deleting?.name??''}」？`} {busy} onconfirm={remove}/>
