<script lang="ts">
 import { Notice } from '@hasbai/ui/notice';
 import { onMount } from 'svelte';import { Button } from '@hasbai/ui/button';import * as Dialog from '@hasbai/ui/dialog';import { Upload, BookOpen, Download, Pencil, Trash2 } from '@lucide/svelte';
 import type { Api } from '../lib/api';import type { Worldbook } from '../../shared/types';import { parseBook } from '../../shared/cards';import Confirm from '../lib/Confirm.svelte';
 let {api}:{api:Api}=$props();let books=$state<Worldbook[]>([]),loading=$state(true),busy=$state(false),error=$state(''),editError=$state(''),editor=$state(false),current=$state<Worldbook>(),draft=$state(''),deleteOpen=$state(false);let input:HTMLInputElement;
 onMount(()=>{void load();});async function load(){loading=true;error='';try{books=(await api.request<{worldbooks:Worldbook[]}>('worldbooks')).worldbooks;}catch(e){error=(e as Error).message;}finally{loading=false;}}
 async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;busy=true;error='';try{if(file.size>2*1024*1024)throw new Error('世界书超过 2 MB');const raw=JSON.parse(await file.text());parseBook(raw);await api.request('worldbooks','POST',{raw});await load();}catch(e){error=(e as Error).message;}finally{busy=false;input.value='';}}
 async function toggle(book:Worldbook){busy=true;error='';try{await api.request('worldbooks/'+book.id,'PATCH',{enabled:!book.enabled});await load();}catch(e){error=(e as Error).message;}finally{busy=false;}}
 async function save(){busy=true;editError='';try{const raw=JSON.parse(draft);parseBook(raw);await api.request('worldbooks/'+current!.id,'PATCH',{raw});editor=false;await load();}catch(e){editError=(e as Error).message;}finally{busy=false;}}
 async function remove(){busy=true;try{await api.request('worldbooks/'+current!.id,'DELETE');deleteOpen=false;await load();}catch(e){error=(e as Error).message;}finally{busy=false;}}
</script>
<header class="page-head"><div><p class="eyebrow">WORLDS & LORE</p><h1>世界书 <span class="count">{books.length}</span></h1></div><Button disabled={busy} onclick={()=>input.click()}><Upload size={16}/>导入世界书</Button></header><input class="sr-only" tabindex="-1" bind:this={input} type="file" accept=".json" aria-label="导入世界书文件" onchange={upload}/>
{#if error}<Notice variant="error">{error}<Button variant="outline" onclick={load}>重试</Button></Notice>{/if}
{#if loading}<div class="empty" role="status">正在加载世界书…</div>{:else if !error&&!books.length}<div class="empty"><BookOpen size={32}/><h2>世界书为空</h2><Button variant="outline" onclick={()=>input.click()}>导入世界书</Button></div>{:else if !error}<div class="book-list">{#each books as book(book.id)}<article class="book-row"><BookOpen size={24}/><div class="grow"><h2>{book.name}</h2><span class="muted">{book.count} 条设定</span>{#if book.unsupported.length}<div class="tags"><span>扩展仅保留</span>{#each book.unsupported as item}<span>{item}</span>{/each}</div>{/if}</div><div class="actions"><Button variant="outline" disabled={busy} onclick={()=>toggle(book)} aria-pressed={book.enabled}>{book.enabled?'已启用':'已停用'}</Button><Button variant="ghost" aria-label={`编辑 ${book.name}`} onclick={()=>{current=book;draft=JSON.stringify(book.raw,null,2);editError='';editor=true;}}><Pencil size={16}/></Button><Button variant="ghost" aria-label={`导出 ${book.name}`} onclick={()=>api.download('worldbooks/'+book.id+'/export',book.name+'.json').catch(e=>error=e.message)}><Download size={16}/></Button><Button variant="ghost" aria-label={`删除 ${book.name}`} onclick={()=>{current=book;deleteOpen=true;}}><Trash2 size={16}/></Button></div></article>{/each}</div>{/if}
<Dialog.Root bind:open={editor}><Dialog.Content><Dialog.Header><Dialog.Title>{current?.name}</Dialog.Title></Dialog.Header><label for="book-json">世界书 JSON</label><textarea id="book-json" class="code-editor" bind:value={draft} spellcheck="false"></textarea>{#if editError}<Notice variant="error">{editError}</Notice>{/if}<Dialog.Footer><Button variant="outline" disabled={busy} onclick={()=>editor=false}>取消</Button><Button disabled={busy} onclick={save}>{busy?'保存中…':'保存'}</Button></Dialog.Footer></Dialog.Content></Dialog.Root>
<Confirm bind:open={deleteOpen} title={`删除世界书「${current?.name??''}」？`} {busy} onconfirm={remove}/>
