import { describe,it,expect } from 'vitest';import {zipSync,strToU8} from 'fflate';
import { importCard,parseCard,parseBook,crc32 } from './cards';import { activateBook,buildPrompt } from './prompt';import { sseData } from './sse';import {DEFAULT_SETTINGS,type Message} from './types';
export const card={spec:'chara_card_v2',spec_version:'2.0',data:{name:'岚',description:'旅店主人 {{char}}',personality:'沉稳',scenario:'港城',first_mes:'你好，{{user}}。',mes_example:'',system_prompt:'{{original}}',post_history_instructions:'',alternate_greetings:['欢迎'],tags:[],creator:'测试作者',extensions:{unknown:{keep:true}}}};
function chunk(type:string,data:Uint8Array){const result=new Uint8Array(data.length+12),v=new DataView(result.buffer);v.setUint32(0,data.length);result.set(strToU8(type),4);result.set(data,8);v.setUint32(data.length+8,crc32(result.subarray(4,data.length+8)));return result;}
export function png(){const v3={...card,spec:'chara_card_v3',data:{...card.data,name:'V3岚'}};const parts=[new Uint8Array([137,80,78,71,13,10,26,10]),chunk('tEXt',strToU8('chara\0'+Buffer.from(JSON.stringify(card)).toString('base64'))),chunk('tEXt',strToU8('ccv3\0'+Buffer.from(JSON.stringify(v3)).toString('base64'))),chunk('IEND',new Uint8Array())];return new Uint8Array(Buffer.concat(parts));}
describe('portable roleplay content',()=>{
 it('imports V1, V2, V3 and preserves unknown raw extensions',()=>{expect(parseCard(card).raw).toEqual(card);expect(parseCard({name:'V1',description:''}).format).toBe('V1');expect(importCard(png(),'角色.png').card.data.name).toBe('V3岚');});
 it('rejects corrupt PNG, truncated data, unsupported versions and non-card files',()=>{const corrupted=png();corrupted[20]^=1;expect(()=>importCard(corrupted,'bad.png')).toThrow('校验');expect(()=>importCard(png().slice(0,-4),'bad.png')).toThrow();expect(()=>parseCard({spec:'unknown'})).toThrow();expect(()=>importCard(strToU8('{broken'),'bad.json')).toThrow();});
 it('imports CHARX and refuses traversal or oversized decompression',()=>{const zip=zipSync({'card.json':strToU8(JSON.stringify(card))});expect(importCard(zip,'card.charx').card.raw).toEqual(card);expect(()=>importCard(zipSync({'../card.json':strToU8('{}')}),'evil.charx')).toThrow('路径');expect(()=>importCard(zipSync({'card.json':new Uint8Array(13*1024*1024)}),'bomb.charx')).toThrow('超限');});
 it('activates enabled keyword, selective and constant entries within order and priority budgets',()=>{const book=parseBook({name:'港城',entries:[{keys:['港'],content:'港城设定',enabled:true,insertion_order:2},{keys:['港'],secondary_keys:['雨'],selective:true,content:'下雨的港城',insertion_order:1},{keys:[],constant:true,content:'规则',insertion_order:0},{keys:['港'],content:'禁用',enabled:false},{keys:['港'],content:'regex',use_regex:true}]});expect(activateBook(book,[{content:'雨落在港'}],s=>s).map(e=>e.content)).toEqual(['规则','下雨的港城','港城设定']);expect(activateBook(book,[{content:'港'}],s=>s).map(e=>e.content)).not.toContain('下雨的港城');expect(book.unsupported).toContain('regex');});
 it('recursively activates once, respects zero budget and case-sensitive scan depth',()=>{const raw={entries:[{keys:['A'],content:'B',case_sensitive:true},{keys:['B'],content:'A'}],recursive_scanning:true,scan_depth:1};expect(activateBook(parseBook(raw),[{content:'A'}],s=>s)).toHaveLength(2);expect(activateBook(parseBook({...raw,token_budget:0}),[{content:'A'}],s=>s)).toHaveLength(0);expect(activateBook(parseBook(raw),[{content:'A'},{content:'a'}],s=>s)).toHaveLength(0);});
 it('does not put metadata in prompts; expands names and retains the latest complete turn',()=>{const messages:Message[]=Array.from({length:12},(_,i)=>({id:String(i),role:i%2===0?'user':'assistant',content:'old '.repeat(80),status:'completed',ordinal:i,requestId:null,createdAt:i}));messages.push({id:'new',role:'user',content:'{{char}}，我是{{user}}',status:'completed',ordinal:12,requestId:null,createdAt:12});const result=buildPrompt(card,[],messages,DEFAULT_SETTINGS,1000+DEFAULT_SETTINGS.maxTokens);expect(result.messages.at(-1)?.content).toBe('岚，我是旅人');expect(result.messages.map(m=>m.content).join('')).not.toContain('测试作者');expect(result.messages.length).toBeLessThan(messages.length+1);});
 it('rejects an oversized latest input and filters incomplete assistant replies',()=>{const message:Message={id:'1',role:'user',content:'中'.repeat(4000),status:'completed',ordinal:0,requestId:null,createdAt:0};expect(()=>buildPrompt(card,[],[message],DEFAULT_SETTINGS,2000)).toThrow('最新');expect(buildPrompt(card,[],[{...message,role:'assistant',status:'error'}],DEFAULT_SETTINGS,2000).messages).toHaveLength(1);});
 it('parses fragmented Unicode SSE, CRLF and multiline frames',async()=>{const bytes=strToU8('data: 你好\r\n\r\ndata: one\ndata: two\n\n');const stream=new ReadableStream<Uint8Array>({start(c){for(const b of bytes)c.enqueue(new Uint8Array([b]));c.close();}});const out=[];for await(const s of sseData(stream))out.push(s);expect(out).toEqual(['你好','one\ntwo']);});
});
