<script lang="ts">
 import { onMount } from 'svelte';import { Button } from '@hasbai/ui/button';import { LibraryBig, Search, BookOpen, MessageCircle, Settings2, Moon, Sun, LogOut } from '@lucide/svelte';
 import BrandMark from './lib/BrandMark.svelte';
 import Library from './pages/Library.svelte';import Discover from './pages/Discover.svelte';import Worldbooks from './pages/Worldbooks.svelte';import Chat from './pages/Chat.svelte';import Settings from './pages/Settings.svelte';
 import type { Api } from './lib/api';import type { Session } from '../shared/types';
 let {api,logout}:{api:Api;logout:()=>void}=$props();const navigation=[{id:'library',label:'角色库',icon:LibraryBig},{id:'discover',label:'发现',icon:Search},{id:'worldbooks',label:'世界书',icon:BookOpen},{id:'chat',label:'对话',icon:MessageCircle},{id:'settings',label:'设置',icon:Settings2}];
 let page=$state('library'),initialId=$state(''),dark=$state(false),error=$state(''),busy=$state(false);
 onMount(()=>{const valid=location.hash.slice(1);if(navigation.some(n=>n.id===valid))page=valid;dark=localStorage.getItem('tavern-theme')==='dark';document.documentElement.classList.toggle('dark',dark);const update=()=>{const value=location.hash.slice(1);if(navigation.some(n=>n.id===value))page=value;};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);});
 function theme(){dark=!dark;document.documentElement.classList.toggle('dark',dark);localStorage.setItem('tavern-theme',dark?'dark':'light');}
 function navigate(id:string){page=id;location.hash=id;}
 async function onchat(id:string,greeting:number){busy=true;error='';try{const s=await api.request<Session>('sessions','POST',{characterId:id,greeting});initialId=s.id;navigate('chat');}catch(e){error=(e as Error).message;}finally{busy=false;}}
</script>
<a class="skip-link" href="#main">跳到主内容</a><div class="shell"><aside class="sidebar"><a href="#library" class="brand" onclick={()=>navigate('library')}><span class="brand-mark"><BrandMark size={30}/></span><span>Tavern<small>酒馆</small></span></a><nav aria-label="主要导航">{#each navigation as n}<a href={`#${n.id}`} aria-current={page===n.id?'page':undefined} onclick={()=>{initialId='';navigate(n.id);}}><n.icon size={19}/><span>{n.label}</span></a>{/each}</nav><div class="sidebar-bottom"><Button variant="ghost" onclick={theme} aria-label={dark?'切换浅色模式':'切换深色模式'}>{#if dark}<Sun size={18}/>{:else}<Moon size={18}/>{/if}<span>主题</span></Button><Button variant="ghost" onclick={logout}><LogOut size={18}/><span>退出</span></Button></div></aside><main id="main" class:chat-page={page==='chat'} class="content">{#if busy}<p role="status">正在创建对话…</p>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}{#if page==='library'}<Library {api} {onchat}/>{:else if page==='discover'}<Discover {api}/>{:else if page==='worldbooks'}<Worldbooks {api}/>{:else if page==='chat'}<Chat {api} {initialId} onlibrary={()=>navigate('library')}/>{:else}<Settings {api} {dark} ontheme={theme}/>{/if}</main></div>
